
```{r}
install.packages("hardhat")
install.packages("ModelMetrics")
```

```{r}
install.packages("caret", dependencies = c("Depends", "Suggests"))
install.packages("missForest")
```

```{r}
library(caret)
library(tidyverse)
library(missForest)
```

```{r}
full_cell_cycle <- read.csv("control_manifold_allfeatures.csv")
```


## initial feature selection + add in G0
```{r}
excluded_vars <- c("PCNA.foci", "DNA.content", "Unnamed..0.1.1", "annotated.age", "annotated.phase")
#these are non-protein expression features, so not interested in these for our models

cell_cycle <- full_cell_cycle %>%
  select(-all_of(excluded_vars)) %>%
  mutate(ratio = pRB..nuc.median./RB..nuc.median.) %>%
  mutate(phase = ifelse(ratio < 1.6, "G0", phase))
## annotating G0 based on biological threshold, ratio < 1.6
```


## Missingness Analysis
```{r}
cell_cycle %>%
  summarise(across(everything(), ~sum(is.na(.)))) %>%
  pivot_longer(cols = everything(), names_to = "variable", values_to = "NA_count") %>%
  filter(NA_count > 0) %>%
  mutate(color = if_else(NA_count > 0.1*8850, "red", NA)) %>%
  ggplot() +
  geom_bar(aes(x = variable, y = NA_count, fill = color), stat = "identity")
```

```{r}
missingness_vars <- cell_cycle %>%
  summarise(across(everything(), ~sum(is.na(.)))) %>%
  pivot_longer(cols = everything(), names_to = "variable", values_to = "NA_count") %>%
  filter(NA_count > 0.1*8850) %>%
  pull(variable)
#removing features with greater than 10% missingness
```

```{r}
cell_cycle2 <- cell_cycle %>%
  select(-all_of(missingness_vars))
```

## missForest imputation

```{r}
cell_cycle2$phase <- as.factor(cell_cycle2$phase)

cell_cycle_imputed <- missForest(cell_cycle2)$ximp
#missForest imputation
```

## mean imputation

```{r}
#cell_cycle_imputed <- cell_cycle2
#for(i in 1:ncol(cell_cycle_imputed)) {
  #if (is.numeric(cell_cycle_imputed[[i]])) {
  #cell_cycle_imputed[[i]][is.na(cell_cycle_imputed[[i]])] <- mean(cell_cycle_imputed[[i]], na.rm = TRUE)
 # }
#}  
```

## check
```{r}
#cell_cycle_imputed %>%
  #summarise(across(everything(), ~sum(is.na(.)))) %>%
  #pivot_longer(cols = everything(), names_to = "variable", values_to = "NA_count") %>%
  #filter(NA_count > 0)
```

## Standardization

# columns are not standardized
```{r}
mean(cell_cycle_imputed$age)
sd(cell_cycle_imputed$age)
```

```{r}
age_unscale <- cell_cycle_imputed$age
PHATE1_unscale <- cell_cycle_imputed$PHATE_1
PHATE2_unscale <- cell_cycle_imputed$PHATE_2
cell_cycle_standardized <- cell_cycle_imputed %>%
  mutate(across(where(is.numeric), ~ as.numeric(scale(.)))) %>%
  mutate(age = age_unscale,
         PHATE_1 = PHATE1_unscale,
         PHATE_2 = PHATE2_unscale)
#standardizing all numeric entries (only feature entires, so excluding age and PHATE embeddings)
```

```{r}
mean(cell_cycle_standardized$age)
sd(cell_cycle_standardized$age)
```


## export clean data
```{r}
write.csv(cell_cycle_standardized, "cell_cycle_tidied.csv", row.names = FALSE)
```

```{r}
top_features <- read_csv("~/IICD/IICD/mmc3.csv")
top_40 <- slice(top_features, 4:43)
top_40_list <- top_40[[1]]
```

```{r}
converted <- sub("^Int_(?:Med|MeanEdge)_([^_]+)_([^_]+)$", "\\1..\\2.median.", x = top_40_list)
  #sub("^Int_Med_([^_]+)_([^_]+)$", "\\1..\\2.median", top_40_list)
converted2 <- ifelse(grepl("^AreaShape_Area_", converted),
                    paste0(str_to_title(sub("^AreaShape_Area_", "", converted)), ".area"),
                    converted)

converted3 <- c(converted2, "age", "phase")

#stringr work to ensure that the top 40 variable names match the full dataset
```

```{r}
cell_cycle_top40 <- cell_cycle_standardized %>%
  select(all_of(setdiff(converted3, c("cycB1..ring.median.", "Bcl2..nuc.median."))))
```

```{r}
write.csv(cell_cycle_top40, "top40_cell_cycle.csv", row.names = FALSE)
```



